### ISSUE TITLE
ESPhome example

### ISSUE THREAD

**Issue by LukasH47** [LaskaKit/ESPink-Shelf#1]
Po aplikování příkladu pro platformu ESPhome 2023.11.4 instalace a Flash na zařízení proběhne dle logu v pořádku, ale na display se stále zobrazuje "hibernating ....
            again"

log pres WiFi v nastaveném intervalu refresh display zobrazuje

"TIME [D][mail:094]: display 

V definici Yaml se má zobrazit jeden řádek s textem, ale bohužel.

**Comment by Dzarda7** [comment]
Kouknu na to, můžete prosím poslat celý log?

**Comment by LukasH47** [comment]
Od puvodního example tam mám rozdíly. Snad tam nemám nějakou chybu, kterou přehlížím, ale mám tu na stole jiný E-INK a ten s ESPhome funguje dle očekávání.

YAML v ESPHOME
[esp32-epaper-temp-yaml.txt](https://github.com/LaskaKit/ESPink-Shelf/files/13478845/esp32-epaper-temp-yaml.txt)

LOG po flashnutí
[logs_esp32-epaper-temp_run.txt](https://github.com/LaskaKit/ESPink-Shelf/files/13478828/logs_esp32-epaper-temp_run.txt)

**Comment by Dzarda7** [comment]
Projel jsem to (bohužel teď nemůžu vyzkoušet). Podle mě bude chyba v tom, že jste vymazal tu část, která po bootu zapíná display:
`  
on_boot:
    priority: 1000
    then:
      - lambda: |-
          pinMode(2, OUTPUT);
          digitalWrite(2, HIGH);
          delay(100);
` 
Koukněte případně do příkladového kódu. Ve schématu GPIO2 spíná display.
